In [6]:
import numpy as np
x = np.array([1,2,3],np.int32)

In [5]:
print(x)

[1 2 3]


In [13]:
#access array element
print(x[0],x[1])
print(x[2])
print(x[-1])

1 2
3
3


In [14]:
#two dimention array

In [28]:
 x_2d = np.array([[1,2,3],[4,5,6]],np.int32)

In [23]:
print(x_2d)

[[1 2 3]
 [4 5 6]]


In [25]:
#(row,coloum)
#1st row 1st coloum
x_2d[:,0]

array([1, 4])

In [27]:
#1st row last coloum
x_2d[:,-1]

array([3, 6])

In [31]:
x_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
#all row all coloum
print("all row all coloum")
print(x_2d[:,:])
print("all row ''0'' coloum")

print(x_2d[:,0])
print(x_2d[:,1])
print(x_2d[:,2])

all row all coloum
[[1 2 3]
 [4 5 6]]
all row ''0'' coloum
[1 4]
[2 5]
[3 6]


In [34]:
print(x_2d[0,:])
print(x_2d[1,:])


[1 2 3]
[4 5 6]


In [85]:
x_3 = np.array([[1,2,3],[4,5,6],[7,8,9]],np.int32)

In [87]:
print(x_3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [88]:
print('row 2 coloum 2 value')
print(x_3[1,1])
print("-------")
print(x_3[:,0])
print(x_3[:,1])
print(x_3[:,2])

row 2 coloum 2 value
5
-------
[1 4 7]
[2 5 8]
[3 6 9]


In [89]:
x_4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],np.int32)

In [90]:
print(x_4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [91]:
for x in x_4[range(len(x_4))]:
    print('row')
    print(x)
    

row
[1 2 3]
row
[4 5 6]
row
[7 8 9]
row
[10 11 12]


In [99]:
x_3d_array = np.array([[[1,2,3],[4,5,6]],[[7,8,9]]])

In [100]:
x_3d_array.ndim

1

In [101]:
#array properties

In [108]:
x_3d_array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],np.int16)

In [104]:
x_3d_array.ndim

3

In [109]:
print(x_3d_array.shape)
print(x_3d_array.ndim)
print(x_3d_array.size)
print(x_3d_array.nbytes)
print(x_3d_array.dtype)

(2, 2, 3)
3
12
24
int16
